Create pages
Alusp/budget-app pull request #1
Opened 2022-12-23 15:13 UTC by Alusp

## I implemented the following in this PR:

- [ ] Set up the repository and tools.
- [ ] Use Postgres as your database.
- [ ] Use devise for authentication.
- [ ] Validate all user input to make sure that anyone with bad intentions cannot compromise your app.
- [ ] Use a view template engine of my choice (.erb).
- [ ] The project should be deployed and accessible online.
- [ ] Your database schema reflect the following structure:
- [ ] Create my models according to the ERD diagram.
- [ ] Implement the authentication and authorization.

2022-12-23 22:06 UTC, KDlamini requested changes
### Hi @Alusp 🙋‍♀️,  

Great work so far! 💯 
You have done a great job creating a working Budget app using Ruby on Rails. 🎊 
There's always room for improvement. There are some issues that you still need to work on improving your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 

✔️  Database, Models, controllers, routes, and views set up correctly
✔️  User authentication using Devise implemented
✔️  User inputs validated
✔️  App is secured from n + 1 problems
✔️  No linter errors

## Required Changes ♻️
 
**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-23 22:06 UTC, KDlamini commented on README.md
> +# 📖 [your_project_name] <a name="BUDGET APP"></a>
Kindly fix your project name, I still see  `[your_project_name] ` as your project title.

2022-12-23 22:06 UTC, KDlamini commented on README.md
Kindly rename your video link to `presentation video` or similar. There are two links named "Live Demo Link" on your READMe which causes confusion as to which is which.

2022-12-23 22:06 UTC, KDlamini commented on app/views/groups/index.html.erb
> +          <%= link_to "Add new category", new_group_path, class: 'btn btn-outline-dark' %>
Kindly make sure that you follow the design guidelines (colors, typography, and layout) for your buttons.

![image](https://user-images.githubusercontent.com/38088818/209406087-fe0ce0b7-3bdb-4145-8dd7-6eb24888fd23.png)

Your design:
![image](https://user-images.githubusercontent.com/38088818/209405809-72c59c8f-d94e-44fb-8426-a49311bc67be.png)

Required design:
![image](https://user-images.githubusercontent.com/38088818/209406026-7b42c63d-5271-4340-8a36-da0137429e19.png)

Same thing for your transactions/purchases button:
![image](https://user-images.githubusercontent.com/38088818/209406302-ecfa4012-3f3b-4e04-a0be-e3aa576d4fcf.png)

2022-12-24 01:58 UTC, Alusp commented
Alright @KDlamini , Thank you very much for the review, fixing it right away.

2022-12-24 05:54 UTC, uwadonat approved these changes
## Hi @Alusp,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- No linter errors ✔️
- Good pull request message ✔️

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-12-24 08:14 UTC, Alusp commented
Thank you very much for the Review @uwadonat

2022-12-24 08:14 UTC, merged